// Constraints for unique identifiers
CREATE CONSTRAINT dept_code IF NOT EXISTS FOR (p:PhongBan) REQUIRE p.code IS UNIQUE;
CREATE CONSTRAINT emp_id IF NOT EXISTS FOR (e:NhanSu) REQUIRE e.empId IS UNIQUE;
CREATE CONSTRAINT skill_ten IF NOT EXISTS FOR (k:KyNang) REQUIRE k.ten IS UNIQUE;
CREATE CONSTRAINT project_key IF NOT EXISTS FOR (p:DuAn) REQUIRE p.key IS UNIQUE;
CREATE CONSTRAINT tech_ten IF NOT EXISTS FOR (t:CongNghe) REQUIRE t.ten IS UNIQUE;